In [ ]:
import numpy as np
import sklearn as sk
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

# Are random forests deterministic?

During the lecture, someone asked whether random forests are really random. Yes, as the name suggests, a random process is used to obtain the result. There is no real need to understand how randomness is used in detail. You can think of it as similar to drawing a random sample to estimate something for a larger dataset. For example, when conducting a survey or a poll, it is important to select all participants at random. In a different way, random forest models also use randomness.

**But does that mean, our model fit or prediction will be different every time?**


Let's simply look at [an example from the documentation](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html)

We don't really care what `X` and `y` are, nor do we really need to understand the parameters. We just assume that the model does fit _something_.

In [ ]:
X, y = make_regression(n_features=4, n_informative=2)

In [ ]:
regr = RandomForestRegressor(max_depth=2)
regr.fit(X, y)

regr.predict([[0, 0, 0, 0]])

array([-14.99687837])

Ok, that's interesting. What if we train a new identical model on the same data again?

Oh, that's something completely different. So indeed, it is not deterministic. Every run will produce a different result because of the randomness. In practice, this is not really important, because all runs will produce very similar results. If you run a poll, it shouldn't matter whom you ask either. But yes, if you are really lucky and ask only people who vote for the same party, you will get a very inaccurate estimate.

There are some cases where you would like to have randomness while still being completely reproducible. For example, think of the homework: it would be easier to check for a correct solution if everyone gets 7.05 as the result, even if 7.04 is probably just as good an estimate of the magnitude.

That's why `sklearn` provides the parameter `random_state`. You can provide an arbitrary value of your choice, which will guarantee that you get exactly the same result on every run, provided that the inputs are identical:

In [ ]:
regr = RandomForestRegressor(max_depth=2)
regr.fit(X, y)

regr.predict([[0, 0, 0, 0]])

array([-12.22320375])

In [ ]:
regr = RandomForestRegressor(max_depth=2, random_state=42)
regr.fit(X, y)

regr.predict([[0, 0, 0, 0]])

array([-17.52337564])

In [ ]:
regr = RandomForestRegressor(max_depth=2, random_state=42)
regr.fit(X, y)

regr.predict([[0, 0, 0, 0]])

array([-17.52337564])

See also [`random_state` in the scikit-learn documentation](https://scikit-learn.org/stable/glossary.html#term-random_state). NumPy provides the function [`np.seed`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html) to achieve something similar.