WISO100303 / Johannes Schmidt & Peter Regner

# **An introduction to scientific programming**

<br> <br> <br> <br><br> <br> <br> <br>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Numpy

<!-- does not work in Datalore
<img src="numpy-logo.png" style="width: 50%; margin: auto;">
-->
![Numpy logo](images/numpy-logo.png)

# The ndarray data type

In [2]:
import numpy as np

In [3]:
np.array([1., 2., 5.])

array([1., 2., 5.])

**Warning:** confusingly `np.array([1., 2., 5.])` is used to create an array, but the type of the resulting object is `np.ndarray`!

Do not use `np.ndarray()` to create a new `ndarray` object, use `np.array()`!

In [4]:
type(np.array([1., 2., 5.]))

numpy.ndarray

In [5]:
arbitrary_values = np.array([1., 2., 5.])

# Elementwise operations and broadcasting

In [6]:
np.array([1, 2, 3]) + 10

array([11, 12, 13])

In [7]:
np.array([1, 2, 3]) * 10

array([10, 20, 30])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(5)**2

array([ 0, 1, 4, 9, 16])

In [10]:
np.cos(np.arange(5) * 2 * np.pi)

array([1., 1., 1., 1., 1.])

# The Python Scientific Ecosystem

<!-- <br>
<div style="text-align:center">
<img alt="Python scientific ecosystem" src="python-scientific-ecosystem.png" style="height:650px;">
</div> -->

![](images/python-scientific-ecosystem.png)

<small>Source: https://speakerdeck.com/jakevdp/the-state-of-the-stack-scipy-2015-keynote?slide=8</small>

# Why numpy? Performance!

One reason for using Numpy instead of pure Python is performance. 

<img src="images/benchmarks.svg" style="width:750px">



<small>Note that this comparison is not very fair. The Python tests are mostly done with pure Python. One can easily speed-up tests by using numpy or other libraries. Adding ``@numba.jit`` to the Fibonacci test causes a speed up of factor 50 (tested with $n=30$).</small>

<small>Source: https://julialang.org/benchmarks/</small>

Also: vector and matrix operations are way simpler to write, many numerical algorithms implemented

# How fast is Numpy in comparison to pure Python?

No numpy used:

In [11]:
numbers = list(range(10**6))

In [12]:
#%timeit sum(numbers)

Numpy used:

In [13]:
numbers_np = np.array(numbers)

In [14]:
#%timeit numbers_np.sum()

A factor 10 speedup comes usually for free with good simple code, but sometimes a speedup factor of 500 is also not uncommon.

## Exercise 1 - Find the error

A user wants to add 0.5 to 4 values. There is a mistake in the code - find and fix it!

Why does the code not work as written here? Check the docstring of `np.array` to find an answer!

In [15]:
# np.array(1, 2, 3, 42) + 0.5

In [16]:
### BEGIN SOLUTION

In [17]:
np.array([1, 2, 3, 42]) + 0.5

array([ 1.5, 2.5, 3.5, 42.5])

In [ ]:
### END SOLUTION

<div style="color:#555;border-top:1px solid #999;text-align:right;padding:4px;">End of exercise</div>

## Exercise 2 - Plot sine and cosine

Plot $\sin(x)$ and $\cos(4x)$ from -2 to 4.5. Use the function `np.linspace(start, stop)` to generate values for `x`.

The plot should contain two lines: one should be the graph of $\sin(x)$ and one the graph of $\cos(4x)$.

Note: this is very similar to exercise 4 in lecture03.

*Hint:* Use the functions `np.sin(x)` and `np.cos(x)`.

<br>

**Bonus task:**

Plot a line defined by points with coordinates $\cos(x)$ on the x axis and $\sin(x)$ on the y axis for x in the range $[0, 2\pi]$. Can you guess the result before actually plotting it?

Note: The plot in the bonus task is not a function $f(x)$ in the mathematical sense, where each value x is mapped to some value $f(x)$.

You can use this additional matplotlib call to make it look nicer: `plt.gca().set_aspect('equal')`

In [18]:
### BEGIN SOLUTION

In [19]:
x = np.linspace(-2, 4.5, 50)
plt.plot(x, np.sin(x), 'x-', label='sin(x)')
plt.plot(x, np.cos(4*x), 'x-', label='cos(4x)')
plt.legend();

Bonus task:

In [20]:
x = np.linspace(0, 2 * np.pi)
plt.plot(np.sin(x), np.cos(x))
plt.gca().set_aspect('equal')

In [ ]:
### END SOLUTION

<div style="color:#555;border-top:1px solid #999;text-align:right;padding:4px;">End of exercise</div>

## Exercise 3 - Pythagorean identity

Write a function `pythagorean_identity(x)` which calculates $\cos(x)^2 + \sin(x)^2$. Call the function with a numpy array with a range of values from 0 to 7.

Do you know the result before calling the function?

In [21]:
### BEGIN SOLUTION

In [22]:
import numpy as np

def pythagorean_identity(x):
    return np.cos(x)**2 + np.sin(x)**2

pythagorean_identity(np.arange(8))

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
### END SOLUTION

<div style="color:#555;border-top:1px solid #999;text-align:right;padding:4px;">End of exercise</div>

# Accessing elements in Numpy arrays

In [23]:
arbitrary_values

array([1., 2., 5.])

In [24]:
arbitrary_values[2]

5.0

In [25]:
arbitrary_values[0:2]

array([1., 2.])

Note that start/stop before the `:` can be omitted, then the slice runs from the start (i.e. index `0`) or from the end (index `-1`):

In [26]:
arbitrary_values[:2]

array([1., 2.])

In [27]:
arbitrary_values[2:]

array([5.])

In [28]:
arbitrary_values[:]

array([1., 2., 5.])

# Setting elements in Numpy arrays

In [29]:
arbitrary_values

array([1., 2., 5.])

In [30]:
arbitrary_values[2] = 3

In [31]:
arbitrary_values

array([1., 2., 3.])

In [32]:
arbitrary_values[0:2] = 42

In [33]:
arbitrary_values

array([42., 42., 3.])

# Dimensions and shape

Numpy arrays can be multidimensional. They are created by passing a list of lists to `np.array()`:

In [34]:
unity_matrix = np.array([[1., 0., 0.],
                         [0., 1., 0.],
                         [0., 0., 1.]])

Lists are always one-dimensional, but 2D objects can be created by putting lists in lists:

![](images/list-of-lists.svg)

A numpy array can be 2D itself, without nesting objects.

In [35]:
unity_matrix

array([[1., 0., 0.],
 [0., 1., 0.],
 [0., 0., 1.]])

In [36]:
unity_matrix.shape

(3, 3)

Note that `.shape` is an _attribute_ of a numpy array. It uses a very similar syntax to a method, but there are no parenthesis!

In [37]:
unity_matrix[2, 2]

1.0

In [38]:
unity_matrix[2, :]

array([0., 0., 1.])

Note that `len()` probably does not do what you want for multidimensional arrays:

In [39]:
len(unity_matrix)

3

In [40]:
arbitrary_values.shape

(3,)

In [41]:
another_2d_array = np.array([[1, 1, 1, 1],
                             [2, 2, 2, 2]])

In [42]:
another_2d_array.shape

(2, 4)

In Numpy the dimensions are called _axis_ and are numberd starting from 0. If you want to sum along a certain axis, you can do so by using the `sum` method and the `axis` parameter:

In [43]:
another_2d_array.sum(axis=0)

array([3, 3, 3, 3])

In [44]:
another_2d_array.sum(axis=1)

array([4, 8])

In [45]:
another_2d_array[0, :]

array([1, 1, 1, 1])

In [46]:
another_2d_array[0, :].shape

(4,)

## Exercise 4 - Create a matrix with ones surrounded by zeros 

Create a matrix `m` with shape `(4, 4)` by using `np.zeros([4, 4])` and set the inner 4 elements to `1` by using slicing in axis 0 and axis 1. Do not use more than two assignment statements in total for this exercise!

Note: The _inner_ and _outer_ elements of a matrix are no widely used technical terms. With _outer elements_, we simply mean here the first/last row and column. _Inner elements_ are all other matrix values. So in case of a 4x4 matrix, there are 4 inner elements and 12 outer elements.

In [47]:
### BEGIN SOLUTION

In [48]:
import numpy as np

In [49]:
m = np.zeros([4,4])

In [50]:
m[1:3, 1:3] = 1

In [51]:
m

array([[0., 0., 0., 0.],
 [0., 1., 1., 0.],
 [0., 1., 1., 0.],
 [0., 0., 0., 0.]])

In [ ]:
### END SOLUTION

<div style="color:#555;border-top:1px solid #999;text-align:right;padding:4px;">End of exercise</div>

## Exercise 5 - Plot first row and first column

Plot the first row and the first column of the matrix `some_matrix` given below. Can you imagine, how the plot should look like, before plotting?

In [52]:
some_matrix = np.array([[1., 0., 1., 0., 1.],
                        [2., 0., 2., 0., 2.],
                        [3., 0., 3., 0., 3.]])

In [ ]:
### BEGIN SOLUTION

In [54]:
plt.plot(some_matrix[0, :], 'o-')
plt.plot(some_matrix[:, 0], 'o-')

In [ ]:
### END SOLUTION

<div style="color:#555;border-top:1px solid #999;text-align:right;padding:4px;">End of exercise</div>

## Exercise 6 - Sum over rows and columns

Calculate the sum of rows and then the sum of columns of `some_matrix`.

In [55]:
some_matrix = np.array([[1., 0., 1., 0., 1.],
                        [2., 0., 2., 0., 2.],
                        [3., 0., 3., 0., 3.]])

In [56]:
### BEGIN SOLUTION

In [57]:
some_matrix.sum(axis=0)

array([6., 0., 6., 0., 6.])

In [58]:
some_matrix.sum(axis=1)

array([3., 6., 9.])

In [ ]:
### END SOLUTION

<div style="color:#555;border-top:1px solid #999;text-align:right;padding:4px;">End of exercise</div>

# Summary: use Numpy for faster and easier computations with gridded data

Numpy makes calcuations with gridded data:
- faster
- easier

Also there are plenty of common functions available (mean, cosine, sine, filters, ...).

![](images/list-of-lists.png)

Non-gridded data doesn't work very well with Numpy:

Imagine somebody wants to collect the age of each person infected with Covid-19 for each day. One could use a list of lists, i.e. a Python list where each element is a list of integers:

In [59]:
infected_age_per_day = [
    [16, 41],
    [73],
    [40, 24, 83, 29],
    [],
    [64, 13],    
]

In [60]:
infected_age_per_day[2]

[40, 24, 83, 29]

The number of infected person varies, so this is not a regular array with rectangular shape.

One can convert the this lists of lists to a `numpy` array, but it is of dtype `object` and not `int`. This should be avoided!

In [61]:
np.array(infected_age_per_day)

ValueError: ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

Instead we can convert this to a gridded array, if we add a new row for each infected person. In the first column there is a value indicating the day of infection and in the section the age of the person:

In [62]:
infected_day_age = [
    [0, 16],
    [0, 41],
    [1, 73],
    [2, 40],
    [2, 24],
    [2, 83],
    [2, 29],
    [4, 64],
    [4, 13],    
]
np.array(infected_day_age)

array([[ 0, 16],
 [ 0, 41],
 [ 1, 73],
 [ 2, 40],
 [ 2, 24],
 [ 2, 83],
 [ 2, 29],
 [ 4, 64],
 [ 4, 13]])

Note that there is a difference in how [lists](https://en.wikipedia.org/wiki/Linked_list) are stored internally vs how [arrays](https://en.wikipedia.org/wiki/Array_(data_structure)) are [stored internally](https://en.wikipedia.org/wiki/Row-_and_column-major_order).

<small>Source: https://transfem.social/notes/9re0vbzxmg8u1wm7</small>

![Matrix pants meme](images/matrix-pants.png)